# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: II Concurso de Castillos de Arena en favor de ATECE
masthead_title: "II Concurso de Castillos ATECE"
email: castillosatece@gmail.com 
description: >- # this means to ignore newlines until "baseurl:"
  Página de la segunda edición del concurso de castillos de arena en favor
  de ATECE Gipuzkoa en San Sebastián/Donostia.
domain: castillosatece.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://castillosatece.net" # the base hostname & protocol for your site, e.g. http://example.com
repository: "CarMarFu/Castillos-de-Arena"
footer:
  links:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/castillosatece/"
    - label: "ATECE - Gipuzkoa"
      icon: "fa-solid fa-link"
      url: "https://www.atecegipuzkoa.org/"

atom_feed:
  hide: true
# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"
locale: "es-ES"
date_format: "%d-%m-%Y"
search: false
include: ["_pages"]

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Define styles
defaults:
  #_posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
